Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('1','Star Sport','Sport Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('2','Sony Six HD','Sport Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('3','Neo HD','Sport Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('4','Zee News HD','News Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('5','ABP News HD','News Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('6','NDTV','News Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('7','Aaj Tak','News Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('8','Colors HD','Entertainment Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('9','Rishtey HD','Entertainment Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('10','Sab HD','Entertainment Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('11','Baby TV HD','Kids Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('12','Star Sport HD1','Sport Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('13','Star Sport HD2','Sport Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('14','Sony Sport HD1','Sony Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('15','Sony Sport HD2','Sony Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('16','Sony Sport HD1','Sony Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('17','Sony Sport HD2','Sony Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('18','Star Sport HD3','Sport Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('19','ESPN Sport HD1','ESPN Channel');
Insert into CHANNEL (CHANNEL_ID,CHANNEL_NAME,CHANNEL_DESC) values ('20','ESPN Sport HD2','ESPN Channel');